Repository pyfar/pyfar, pull requests merged in 2020-11, with the labels that each got.

#1 Implement Filter Object
  docs/pyfar.classes.rst
  pyfar/dsp/__init__.py
  pyfar/dsp/_audiofilter.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter.py
  tests/test_filter.py
Labels: enhancement

#5 Move filter classes into separate file
  pyfar/dsp/__init__.py
  pyfar/dsp/classes.py
  pyfar/dsp/filter.py
  tests/test_filter_classes.py
Labels: enhancement

#8 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#6 Feature sofa read
  examples/pyfar_demo.ipynb
  pyfar/__init__.py
  pyfar/io.py
  requirements_dev.txt
  tests/test_io.py
  tests/test_io_data/GeneralFIR.sofa
  tests/test_io_data/GeneralFIR_postype.sofa
  tests/test_io_data/GeneralFIR_unit.sofa
  tests/test_io_data/GeneralTF.sofa
  tests/test_io_data/generate_test_io_data.py
Labels: enhancement

#4 Refactoring arithmetic
  examples/pyfar_demo.ipynb
  pyfar/arithmetic.py
  pyfar/signal.py
  tests/test_signal_arithmetic.py
Labels: documentation, enhancement

#17 Delete plot.py
  pyfar/plot/plot.py
Labels: plot

#19 Filter comment
  pyfar/dsp/classes.py
  pyfar/dsp/filter.py
  tests/test_filter_classes.py
Labels: enhancement, filter

#18 Enhacement signal
  pyfar/dsp/classes.py
  pyfar/signal.py
  tests/test_filter_classes.py
  tests/test_io.py
  tests/test_io_data/GeneralFIR_unit.sofa
  tests/test_signal.py
Labels: enhancement, signal

#25 Add sampling rate to filter class objects
  pyfar/dsp/classes.py
  pyfar/dsp/filter.py
  tests/test_filter_classes.py
Labels: enhancement, filter

#27 update requirements in txt file and setup.py
  README.rst
  pyfar/plot/gui.py
  requirements_dev.txt
  setup.py
Labels: enhancement

#34 Feature testing filters
  pyfar/dsp/filter.py
  tests/test_dsp.py
  tests/test_filter.py
Labels: feature, filter

#32 added workflow for automatic project assignment
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/assign_to_project.yml
Labels: feature
