Repository pyfar/pyfar, pull requests merged in 2021-03, with the labels that each got.

#114 Replace deprecated numpy types by builtins
  pyfar/_codec.py
  pyfar/dsp/filter.py
  pyfar/plot/ticker.py
  pyfar/signal.py
  pyfar/spatial/external/eq_area_partitions.py
  pyfar/spatial/samplings.py
  pyfar/testing/stub_utils.py
  tests/test_eq_area_partitions.py
  tests/test_stub_utils.py
Labels: dependencies

#104 Enhancement/testing guidelines
  CONTRIBUTING.rst
Labels: documentation, enhancement

#101 Faster group delay calculation
  pyfar/dsp/dsp.py
  tests/test_dsp.py
Labels: feature

#109 Enhancement/write wav checks
  pyfar/io.py
  tests/test_io.py
Labels: enhancement, io

#106 Enhancement/plotstyle context manager
  pyfar/plot/line.py
  pyfar/plot/utils.py
  tests/test_plot.py
  tests/test_plot_data/baseline/use_dark.png
  tests/test_plot_data/baseline/use_default.png
Labels: feature, plot

#84 Enable plotting TimeData and FrequencyData objects
  pyfar/__init__.py
  pyfar/dsp/dsp.py
  pyfar/plot/_interaction.py
  pyfar/plot/_line.py
  pyfar/plot/line.py
  pyfar/plot/utils.py
  pyfar/testing/stub_utils.py
  tests/conftest.py
  tests/test_dsp.py
  tests/test_plot.py
  tests/test_plot_data/baseline/line_frequency_data_freq.png
  tests/test_plot_data/baseline/line_frequency_data_freq_phase.png
  tests/test_plot_data/baseline/line_frequency_data_phase.png
  tests/test_plot_data/baseline/line_time_data_time.png
  tests/test_plot_data/baseline/line_time_hold.png
  tests/test_stub_utils.py
Labels: enhancement, plot

#119 updated docstring with new short cuts
  pyfar/plot/utils.py
Labels: documentation

#120 Updated Fliege-Maier samplings for consitency
  pyfar/spatial/samplings.py
Labels: coordinates, enhancement

#123 Coordinates __getitem__ bugfix
  pyfar/coordinates.py
  tests/test_coordinates.py
Labels: bug, coordinates

#99 Regularized spectrum inversion
  pyfar/dsp/__init__.py
  pyfar/dsp/dsp.py
  pyfar/testing/stub_utils.py
  tests/test_dsp.py
Labels: dsp, feature

#126 Feature/signals
  pyfar/signals/__init__.py
  pyfar/signals/deterministic.py
  pyfar/signals/stochastic.py
  tests/references/signals.exponential_sweep.csv
  tests/references/signals.exponential_sweep.py
  tests/references/signals.linear_sweep.csv
  tests/references/signals.linear_sweep.py
  tests/test_signals.py
Labels: dsp, feature

#131 restricted range of python version
  setup.py
Labels: feature

#130 Run CI against wheel binaries
  requirements_dev.txt
  tox.ini
Labels: ci

#124 Init structure for imports
  pyfar/__init__.py
  pyfar/coordinates.py
  pyfar/dsp/__init__.py
  pyfar/dsp/classes.py
  pyfar/dsp/dsp.py
  pyfar/dsp/fft.py
  pyfar/plot/__init__.py
  pyfar/signal.py
  pyfar/signals/deterministic.py
  pyfar/signals/stochastic.py
  pyfar/spatial/__init__.py
  pyfar/spatial/spatial.py
  pyfar/utils.py
  tests/conftest.py
  tests/test_copy.py
  tests/test_fft.py
  tests/test_fractional_octaves.py
  tests/test_imports.py
  tests/test_spatial.py
Labels: enhancement

#128 Enhancement/signal test fixtures
  pyfar/testing/stub_utils.py
  tests/conftest.py
  tests/test_copy.py
  tests/test_dsp.py
  tests/test_fft.py
  tests/test_filter.py
  tests/test_filter_classes.py
  tests/test_frequency_data.py
  tests/test_io.py
  tests/test_plot.py
  tests/test_signal.py
  tests/test_stub_utils.py
  tests/test_time_data.py
Labels: enhancement, fft, filter, io, plot, signal
