Repository pyfar/pyfar, pull requests merged in 2021-04, with the labels that each got.

#138 Add info@pyfar and pyfar.org
  README.rst
  docs/modules.rst
  docs/pyfar.io.rst
  pyfar/io.py
  setup.py
Labels: documentation

#145 Bugfix for ignored channels during processing of multi-channel signals in filter classes
  pyfar/dsp/classes.py
  tests/test_filter_classes.py
Labels: bug, filter

#141 Documentation for audio classes
  docs/pyfar.classes_audio.rst
  pyfar/signal.py
  tests/test_frequency_data.py
  tests/test_signal.py
  tests/test_time_data.py
Labels: documentation

#140 Documentation for pyfar.signals
  pyfar/signals/__init__.py
  pyfar/signals/deterministic.py
  pyfar/signals/stochastic.py
  tests/test_signals.py
Labels: documentation

#143 Read the docs/io
  pyfar/io.py
Labels: documentation, io

#136 Added documentation guidelines
  CONTRIBUTING.rst
Labels: documentation

#134 Enhancement/update testing guidelines
  CONTRIBUTING.rst
Labels: documentation, enhancement

#139 Documentation for pyfar.coordinates
  docs/resources/coordinate_systems.ai
  docs/resources/coordinate_systems.png
  pyfar/coordinates.py
Labels: documentation

#133 Update example notebook
  examples/pyfar_demo.ipynb
Labels: documentation, enhancement

#148 Rename pyfar.spatial to pyfar.samplings
  .gitignore
  examples/pyfar_demo.ipynb
  pyfar/__init__.py
  pyfar/samplings/__init__.py
  pyfar/samplings/external/__init__.py
  pyfar/samplings/external/eq_area_partitions.py
  pyfar/samplings/external/samplings_fliege.mat
  pyfar/samplings/external/samplings_lebedev.py
  pyfar/samplings/samplings.py
  pyfar/samplings/spatial.py
  pyfar/spatial/__init__.py
  tests/conftest.py
  tests/test_eq_area_partitions.py
  tests/test_imports.py
  tests/test_io.py
  tests/test_samplings.py
  tests/test_spatial.py
Labels: enhancement, spatial

#149 changed fft normalization of sweep signals to none
  pyfar/signals/deterministic.py
  tests/test_signals.py
Labels: enhancement, signal

#137 Documentation for pyfar.plot
  docs/pyfar.plot.rst
  pyfar/plot/__init__.py
  pyfar/plot/line.py
  pyfar/plot/utils.py
  tests/test_plot_utils.py
Labels: documentation

#147 Extend documentation of Filter objects and functions.
  docs/modules.rst
  docs/pyfar.classes_filter.rst
  docs/pyfar.dsp.filter.rst
  docs/pyfar.dsp.rst
  pyfar/dsp/classes.py
  pyfar/dsp/filter.py
Labels: documentation, filter

#154 update exmple nb binder link to main branch
  README.rst
Labels: documentation

#153 Fix wrong path for external sampiling *.mat files
  MANIFEST.in
Labels: bug, spatial

#156 Move io files into separate folder and adjust imports
  pyfar/io/__init__.py
  pyfar/io/_codec.py
  pyfar/io/io.py
  tests/test_codec.py
  tests/test_io.py
Labels: enhancement, io

#157 Read the docs: dsp
  pyfar/dsp/fft.py
  pyfar/dsp/filter.py
Labels: documentation, dsp, enhancement

#158 Read the docs: plots
  pyfar/plot/line.py
Labels: documentation, plot

#159 Read the docs: samplings
  pyfar/samplings/spatial.py
Labels: documentation, spatial

#160 Read the docs signals
  pyfar/signals/deterministic.py
  pyfar/signals/stochastic.py
Labels: documentation, dsp

#161 updated contribution guidline for referencing pyfar modules, classes, and functions
  CONTRIBUTING.rst
Labels: documentation

#155 Use Travis to deploy to PyPI
  .travis.yml
Labels: ci

#165 Remove keyword 'line' from shortcuts
  pyfar/plot/_interaction.py
  pyfar/plot/line.py
  pyfar/plot/shortcuts/shortcuts.json
Labels: enhancement, plot

#167 Fix broken links in doc summary tables generated by autodocsumm
  pyfar/classes/coordinates.py
  pyfar/classes/filter.py
  pyfar/classes/orientations.py
  pyfar/dsp/filter.py
Labels: bug, documentation

#168 Fix Matplotlib deprecated warning for scatter plot
  pyfar/plot/spatial.py
Labels: bug, plot

#171 Revise testing for coordinates
  pyfar/classes/coordinates.py
  tests/test_coordinates.py
Labels: bug, coordinates, enhancement

#164 Improve documentation for dsp.fft
  pyfar/dsp/fft.py
Labels: documentation, dsp

#173 Use parametrization for fft tests
  tests/conftest.py
  tests/test_fft.py
Labels: ci, fft
