Repository pyfar/pyfar, pull requests merged in 2022-08, with the labels that each got.

#334 Hotfix for broken soundfile import on some machines
  pyfar/io/io.py
Labels: hot, io

#340 Bugfix exception catching for soundfile import
  pyfar/io/io.py
Labels: hot, bug, dependencies

#342 fixed type in FrequencyData for default type complex
  pyfar/classes/audio.py
Labels: documentation, enhancement
