Repository pyfar/pyfar, pull requests merged in 2022-11, with the labels that each got.

#377 update urls for the project, code repo and docs
  setup.py
Labels: documentation, enhancement

#378 Fix/binder
  CONTRIBUTING.rst
  environment.yml
Labels: hot, bug

#379 Use emtpy string for empty comments
  pyfar/classes/audio.py
  pyfar/classes/coordinates.py
  pyfar/classes/filter.py
  pyfar/dsp/dsp.py
  tests/test_audio.py
  tests/test_audio_signal.py
  tests/test_dsp_average.py
  tests/test_filter_classes.py
Labels: enhancement, audio
