Repository pyfar/pyfar, pull requests merged in 2022-01, with the labels that each got.

#253 Complete rules for arithmetics
  pyfar/classes/audio.py
  tests/test_signal_arithmetic.py
Labels: enhancement

#256 Bugfixes for spectrogram functions
  pyfar/dsp/dsp.py
  pyfar/plot/_interaction.py
  pyfar/plot/_line.py
  pyfar/plot/_two_d.py
  pyfar/plot/line.py
  tests/test_dsp_spectrogram.py
  tests/test_plot.py
Labels: bug, dsp, plot

#251 Enhancement/concepts
  docs/concepts.rst
  docs/concepts/pyfar.arithmetic_operations.rst
  docs/concepts/pyfar.audio_classes.rst
  docs/concepts/pyfar.coordinates.rst
  docs/concepts/pyfar.fft.rst
  docs/concepts/pyfar.filter.rst
  docs/concepts/pyfar.filter_classes.rst
  docs/concepts/pyfar.filter_types.rst
  docs/concepts/pyfar.plot.rst
  docs/concepts/resources/fft_norms.py
  docs/concepts/resources/fft_norms_examples.png
  docs/concepts/resources/filter_types.py
  docs/concepts/resources/filter_types_crossover.png
  docs/concepts/resources/filter_types_filterbanks.png
  docs/concepts/resources/filter_types_parametric-eq.png
  docs/concepts/resources/filter_types_standard.png
  docs/resources/pyfar.dsp.filter.types.png
  docs/resources/pyfar.dsp.filter.types.py
  pyfar/_concepts/arithmetic_operations.py
  pyfar/_concepts/arithmetic_operations_concepts.py
  pyfar/_concepts/audio_classes.py
  pyfar/_concepts/audio_concepts.py
  pyfar/_concepts/coordinates.py
  pyfar/_concepts/coordinates_concepts.py
  pyfar/_concepts/fft.py
  pyfar/_concepts/fft_concepts.py
  pyfar/_concepts/filter_classes.py
  pyfar/_concepts/filter_types.py
  pyfar/_concepts/plots.py
  pyfar/classes/audio.py
  pyfar/classes/coordinates.py
  pyfar/classes/filter.py
  pyfar/dsp/filter.py
  pyfar/plot/__init__.py
Labels: documentation, enhancement

#263 Bugfix/micro seconds label in plots
  pyfar/plot/_utils.py
  tests/test_plot__utils.py
Labels: bug, plot

#261 Enhancement: contributing
  AUTHORS.rst
  CONTRIBUTING.rst
Labels: documentation, enhancement

#264 Update history
  HISTORY.rst
Labels: documentation

#270 Feature/normalization and averaging
  examples/diagram.png
  examples/presentation.ipynb
  pyfar/dsp/dsp.py
  tests/test_dsp.py
Labels: feature, dsp
