Repository pyfar/pyfar, pull requests merged in 2022-02, with the labels that each got.

#269 Update Contributions
  CONTRIBUTING.rst
Labels: documentation

#275 Bugfix/remove C._t file from tests
  tests/test_io.py
Labels: bug, io

#282 freq_scale parameter for 2D plots
  pyfar/plot/two_d.py
  tests/test_plot.py
  tests/test_plot_data/baseline/freq_2d_freq_scale_linear.png
  tests/test_plot_data/baseline/freq_2d_freq_scale_log.png
  tests/test_plot_data/baseline/freq_2d_xscale_linear.png
  tests/test_plot_data/baseline/freq_2d_xscale_log.png
  tests/test_plot_data/baseline/group_delay_2d_freq_scale_linear.png
  tests/test_plot_data/baseline/group_delay_2d_freq_scale_log.png
  tests/test_plot_data/baseline/group_delay_2d_xscale_linear.png
  tests/test_plot_data/baseline/group_delay_2d_xscale_log.png
  tests/test_plot_data/baseline/phase_2d_freq_scale_linear.png
  tests/test_plot_data/baseline/phase_2d_freq_scale_log.png
  tests/test_plot_data/baseline/phase_2d_xscale_linear.png
  tests/test_plot_data/baseline/phase_2d_xscale_log.png
Labels: plot

#281 complete docstring
  pyfar/dsp/filter.py
Labels: documentation
