Repository pyfar/pyfar, pull requests merged in 2023-01, with the labels that each got.

#418 Deprecate len(Signal)
  pyfar/classes/audio.py
  tests/test_deprecations.py
Labels: enhancement

#409 Fix bugs and failing test caused by numpy update
  pyfar/dsp/dsp.py
  tests/test_dsp_normalize.py
Labels: hot

#415 Reading Sofa files of type FIR-E and TF-E
  pyfar/io/io.py
  tests/conftest.py
  tests/test_io.py
Labels: hot, io

#417 Hot/read comsol
  pyfar/io/io.py
  tests/test_io_comsol.py
  tests/test_io_data/intensity_product.csv
  tests/test_io_data/intensity_product.dat
  tests/test_io_data/intensity_product.txt
Labels: hot

#422 show plot shortcuts in sphinx docs
  docs/concepts/pyfar.plot.rst
  docs/concepts/resources/plot_shortcuts.rst
  docs/conf.py
  pyfar/plot/utils.py
  tests/test_plot_utils.py
Labels: documentation, plot

#423 Improve documentation plots time unit
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/fractional_octaves.py
  pyfar/dsp/filter/gammatone.py
  pyfar/dsp/interpolation.py
  pyfar/plot/line.py
  pyfar/plot/two_d.py
Labels: documentation, enhancement
