Repository pyfar/pyfar, pull requests merged in 2023-10, with the labels that each got.

#476 Deprecations for Pyfar 0.6.0
  pyfar/plot/_utils.py
  pyfar/plot/line.py
  pyfar/plot/two_d.py
  tests/test_deprecations.py
Labels: documentation

#477 Avoid warnings in tests
  pyfar/dsp/dsp.py
  pyfar/samplings/samplings.py
Labels: ci

#396 add complex argument to TimeData
  pyfar/classes/audio.py
  pyfar/dsp/fft.py
  pyfar/testing/stub_utils.py
  tests/conftest.py
  tests/test_audio_signal.py
  tests/test_audio_time_data.py
  tests/test_fft.py
Labels: enhancement, feature, audio, fft

#407 Update testing guidelines
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
  tests/test_filter.py
  tests/test_filter_shelve_cascade.py
Labels: ci, v0.6.0

#486 Samplings deprecation and shift to spharpy
  docs/conf.py
  examples/pyfar_demo.ipynb
  pyfar/classes/coordinates.py
  pyfar/samplings/samplings.py
  pyfar/samplings/spatial.py
  tests/test_deprecations.py
Labels: coordinates, v0.7.0

#478 refactor find*
  examples/pyfar_demo.ipynb
  pyfar/classes/coordinates.py
  tests/test_coodinates_find.py
  tests/test_coordinates.py
  tests/test_deprecations.py
Labels: coordinates, v0.6.0

#459 Update dsp.average for complex signals
  pyfar/dsp/dsp.py
  tests/test_dsp_average.py
Labels: complex-signal, v0.7.0

#464 check and test audio arithmetic for complex-valued data
  pyfar/classes/audio.py
  tests/test_audio_signal_arithmetic.py
Labels: complex-signal

#500 Add `rad2deg` and `deg2rad`
  pyfar/__init__.py
  pyfar/classes/coordinates.py
  tests/test_coordinates_new.py
Labels: feature, coordinates, v0.6.0

#509 Fix/examples notebook
  examples/pyfar_demo.ipynb
Labels: documentation, bug

#507 add deprecation for 'deg'
  pyfar/classes/coordinates.py
Labels: coordinates, v0.6.0

#499 Fix pyfar not running in read only containers
  pyfar/signals/files.py
Labels: bug

#498 remove Coordinates.__init__ from docs
  docs/classes/pyfar.coordinates.rst
  pyfar/classes/coordinates.py
Labels: documentation
