Repository pyfar/pyfar, pull requests merged in 2024-09, with the labels that each got.

#614 ruff: check docstring format
  pyfar/classes/__init__.py
  pyfar/classes/audio.py
  pyfar/classes/filter.py
  pyfar/classes/orientations.py
  pyfar/classes/warnings.py
  pyfar/dsp/__init__.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/audiofilter.py
  pyfar/dsp/filter/band_filter.py
  pyfar/dsp/filter/fractional_octaves.py
  pyfar/dsp/filter/gammatone.py
  pyfar/dsp/interpolation.py
  pyfar/io/__init__.py
  pyfar/plot/line.py
  pyfar/plot/ticker.py
  pyfar/plot/two_d.py
  pyfar/plot/utils.py
  pyfar/samplings/external/__init__.py
  pyfar/samplings/samplings.py
  pyfar/samplings/spatial.py
  pyfar/signals/deterministic.py
  pyfar/signals/stochastic.py
  pyfar/testing/stub_utils.py
  pyproject.toml
Labels: ci, v0.8.0, cookiecutter

#683 deprecate Python 3.8
  .circleci/config.yml
  README.md
  setup.py
Labels: dependencies, v0.7.0

#687 ruff: FIX Code should not contain FIXME, TODO, etc.
  pyproject.toml
Labels: ci, v0.8.0, code-style

#694 Remove unwanted warning in Coordinates initialization
  pyfar/classes/coordinates.py
  pyfar/dsp/filter/_audiofilter.py
Labels: hot, coordinates, v0.6.9

#691 Ruff: I002,TID252 import stuff
  pyfar/plot/two_d.py
  pyproject.toml
Labels: ci, v0.8.0, code-style

#689 Ruff: COM, trailing comma rules
  pyfar/classes/__init__.py
  pyfar/classes/coordinates.py
  pyfar/dsp/__init__.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/__init__.py
  pyfar/io/io.py
  pyfar/plot/__init__.py
  pyfar/plot/ticker.py
  pyfar/testing/stub_utils.py
  pyproject.toml
  tests/test_coordinates.py
  tests/test_coordinates_find.py
  tests/test_dsp_average.py
  tests/test_dsp_interpolation.py
  tests/test_fft.py
  tests/test_filter_classes.py
  tests/test_filter_gammatone.py
  tests/test_io.py
  tests/test_io_comsol.py
  tests/test_plot.py
  tests/test_plot_interaction.py
  tests/test_signals.py
  tests/test_signals_files.py
Labels: ci, v0.8.0, code-style

#688 Ruff: NPY Check all numpy related deprecations
  pyfar/testing/stub_utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_audio_frequency_data.py
  tests/test_audio_signal.py
  tests/test_audio_time_data.py
  tests/test_dsp.py
  tests/test_spatial.py
Labels: ci, v0.7.0, code-style

#686 ruff: ERA no commented code
  pyfar/classes/audio.py
  pyfar/classes/coordinates.py
  pyfar/classes/orientations.py
  pyfar/dsp/filter/_audiofilter.py
  pyfar/dsp/filter/audiofilter.py
  pyfar/dsp/interpolation.py
  pyfar/samplings/external/eq_area_partitions.py
  pyproject.toml
  tests/test_coordinates.py
  tests/test_coordinates_new.py
  tests/test_copy.py
  tests/test_dsp.py
Labels: ci, v0.8.0, code-style

#702 Complex signals: fix ``side`` docstring
  pyfar/plot/line.py
  pyfar/plot/two_d.py
Labels: plot, complex-signal, v0.7.0

#696 hot: wait for test_deprecation_warnings before release
  .circleci/config.yml
Labels: ci, v0.6.10

#704 fix ruff on dev complex after merging dev into it
  tests/test_dsp.py
Labels: ci, complex-signal, v0.7.0

#703 Fix unit string in group delay plot
  pyfar/plot/_two_d.py
Labels: bug, plot, v0.7.0

#690 Ruff: A, Avoid builtin function and type shadowing.
  pyfar/classes/filter.py
  pyfar/dsp/interpolation.py
  pyfar/io/io.py
  pyfar/testing/stub_utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_coordinates_new.py
  tests/test_deprecations.py
  tests/test_dsp.py
  tests/test_dsp_interpolation.py
  tests/test_filter_classes.py
  tests/test_filter_gammatone.py
  tests/test_io.py
  tests/test_io_comsol.py
Labels: ci, v0.7.0, code-style

#682 Replace scipy's legacy spectrogram with new implementaton
  pyfar/dsp/dsp.py
Labels: dsp, dependencies, v0.7.0

#680 add arithmetics for coordinates
  pyfar/__init__.py
  pyfar/classes/coordinates.py
  tests/test_coordiantes_arithmetic.py
Labels: v0.7.0

#652 Update interaction
  docs/resources/plot_shortcuts.rst
  pyfar/plot/_interaction.py
  pyfar/plot/line.py
  pyfar/plot/shortcuts/shortcuts.json
  pyfar/plot/two_d.py
  pyfar/plot/utils.py
  tests/test_dsp.py
  tests/test_plot_interaction.py
  tests/test_plot_utils.py
Labels: complex-signal, v0.7.0

#636 Feature/transmission matrix
  docs/api_reference.rst
  docs/classes/pyfar.transmission_matrix.rst
  pyfar/__init__.py
  pyfar/classes/__init__.py
  pyfar/classes/audio.py
  pyfar/classes/transmission_matrix.py
  pyfar/io/_codec.py
  tests/test_imports.py
  tests/test_io.py
  tests/test_transmission_matrix.py
  tests/test_transmission_matrix_derived_parameters.py
  tests/test_transmission_matrix_multiplication.py
Labels: v0.7.0

#684 Show paths as imported in pyfar
  docs/classes/pyfar.audio.rst
  docs/classes/pyfar.coordinates.rst
  docs/classes/pyfar.filter.rst
  docs/classes/pyfar.orientations.rst
  pyfar/classes/coordinates.py
  pyfar/classes/filter.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/audiofilter.py
  pyfar/dsp/interpolation.py
  pyfar/io/io.py
  pyfar/signals/deterministic.py
Labels: documentation, v0.7.0

#325 Soft limiting
  pyfar/dsp/__init__.py
  pyfar/dsp/dsp.py
  tests/test_dsp_soft_limit_spectrum.py
Labels: feature, dsp, v0.7.0

#707 hot: fix compress flag in pyfar.io.write
  pyfar/io/io.py
  tests/test_io.py
Labels: hot, io, v0.6.10

#697 ruff: ARG, no unused arguments
  pyfar/classes/coordinates.py
  pyfar/classes/orientations.py
  pyfar/dsp/filter/_audiofilter.py
  pyfar/plot/ticker.py
  pyfar/plot/utils.py
  pyfar/samplings/external/eq_area_partitions.py
  pyproject.toml
  tests/test_dsp.py
  tests/test_io.py
  tests/test_orientations.py
Labels: ci, v0.7.0, code-style

#708 add verbose to read_sofa
  pyfar/io/io.py
Labels: v0.7.0, v0.8.0

#709 fix typo and parameter properties in Transmission Matrix
  pyfar/classes/transmission_matrix.py
Labels: bug, v0.7.0

#705 Release v0.7.0
  HISTORY.rst
Labels: v0.7.0

#692 Ruff: PT
  pyfar/testing/stub_utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_audio_frequency_data.py
  tests/test_audio_signal.py
  tests/test_audio_signal_arithmetic.py
  tests/test_audio_signal_iterator.py
  tests/test_audio_time_data.py
  tests/test_coordiantes_arithmetic.py
  tests/test_coordinates.py
  tests/test_coordinates_find.py
  tests/test_coordinates_new.py
  tests/test_deprecations.py
  tests/test_dsp.py
  tests/test_dsp_average.py
  tests/test_dsp_decibel.py
  tests/test_dsp_energy_power_rms.py
  tests/test_dsp_interpolation.py
  tests/test_dsp_normalize.py
  tests/test_dsp_soft_limit_spectrum.py
  tests/test_dsp_spectrogram.py
  tests/test_fft.py
  tests/test_filter.py
  tests/test_filter_classes.py
  tests/test_filter_gammatone.py
  tests/test_filter_shelve_cascade.py
  tests/test_io.py
  tests/test_io_comsol.py
  tests/test_match_fft_norm.py
  tests/test_orientations.py
  tests/test_plot.py
  tests/test_plot__utils.py
  tests/test_plot_interaction.py
  tests/test_pyfar.py
  tests/test_samplings.py
  tests/test_signals_files.py
  tests/test_stub_utils.py
  tests/test_transmission_matrix.py
  tests/test_utils.py
Labels: ci, v0.8.0, code-style

#698 Ruff: B Bugbear
  pyfar/_utils.py
  pyfar/classes/audio.py
  pyfar/classes/coordinates.py
  pyfar/classes/filter.py
  pyfar/classes/orientations.py
  pyfar/classes/transmission_matrix.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/audiofilter.py
  pyfar/dsp/filter/fractional_octaves.py
  pyfar/dsp/filter/gammatone.py
  pyfar/dsp/interpolation.py
  pyfar/io/_codec.py
  pyfar/io/io.py
  pyfar/plot/_two_d.py
  pyfar/samplings/samplings.py
  pyfar/samplings/spatial.py
  pyfar/signals/deterministic.py
  pyfar/signals/files.py
  pyproject.toml
  tests/test_audio_frequency_data.py
  tests/test_audio_signal_iterator.py
  tests/test_audio_time_data.py
  tests/test_coordinates_new.py
  tests/test_deprecations.py
  tests/test_io_comsol.py
  tests/test_warnings.py
Labels: ci, v0.8.0, code-style
