Repository pyfar/pyfar, pull requests merged in 2024-12, with the labels that each got.

#728 Enhance head-related impulse responses
  pyfar/signals/files.py
  tests/test_signals_files.py
Labels: bug, signals, v0.7.1

#722 Normaliztation: Force energetic properties to match the target after normalization
  pyfar/dsp/dsp.py
  tests/test_dsp_normalize.py
Labels: bug, dsp, v0.7.1

#733 bugfix from merge main into dev
  pyfar/dsp/__init__.py
Labels: bug, v0.8.0

#737 fix bug from matplotlib 3.10
  pyfar/plot/_interaction.py
Labels: hot, v0.7.1

#725 deprecate 'frequencies' reconstructing_fractional_octave_bands()
  pyfar/dsp/filter/fractional_octaves.py
  tests/test_deprecations.py
Labels: discuss, v0.7.1

#736 return exact results for octave and third octave for limits out of range
  pyfar/dsp/filter/fractional_octaves.py
  tests/test_fractional_octaves.py
Labels: hot, v0.7.1
