Repository pyfar/pyfar, pull requests merged in 2024-06, with the labels that each got.

#590 Update readme and contributing
  CONTRIBUTING.rst
  README.rst
  docs/index.rst
Labels: documentation, cookiecutter, 0.6.6

#591 Documentation/remove concepts
  docs/classes/resources/coordinate_systems.ai
  docs/classes/resources/coordinate_systems.png
  docs/concepts.rst
  docs/concepts/pyfar.arithmetic_operations.rst
  docs/concepts/pyfar.audio_classes.rst
  docs/concepts/pyfar.coordinates.rst
  docs/concepts/pyfar.fft.rst
  docs/concepts/pyfar.filter_classes.rst
  docs/concepts/pyfar.filter_types.rst
  docs/concepts/pyfar.plot.rst
  docs/concepts/resources/fft_norms.py
  docs/concepts/resources/fft_norms_examples.png
  docs/concepts/resources/filter_types.py
  docs/concepts/resources/filter_types_audio_filter_1.png
  docs/concepts/resources/filter_types_audio_filter_2.png
  docs/concepts/resources/filter_types_crossover.png
  docs/concepts/resources/filter_types_filterbanks.png
  docs/concepts/resources/filter_types_standard.png
  docs/conf.py
  docs/index.rst
  docs/modules/pyfar.dsp.filter.rst
  docs/pyfar.rst
  docs/resources/plot_shortcuts.rst
  pyfar/_concepts/arithmetic_operations.py
  pyfar/_concepts/audio_classes.py
  pyfar/_concepts/coordinates.py
  pyfar/_concepts/fft.py
  pyfar/_concepts/filter_classes.py
  pyfar/_concepts/filter_types.py
  pyfar/_concepts/plots.py
  pyfar/classes/audio.py
  pyfar/classes/coordinates.py
  pyfar/classes/filter.py
  pyfar/dsp/dsp.py
  pyfar/dsp/fft.py
  pyfar/dsp/filter/__init__.py
  pyfar/plot/__init__.py
  pyfar/plot/utils.py
  pyfar/samplings/__init__.py
  pyfar/utils.py
Labels: documentation, 0.6.6

#617 Fix bug in `Coordinates.find within`
  pyfar/classes/coordinates.py
  tests/test_coordinates_find.py
Labels: hot, coordinates, 0.6.6

#606 Relax arithmetic rules in case only one audio object is involved
  pyfar/classes/audio.py
  tests/test_audio_signal_arithmetic.py
Labels: hot, audio, 0.6.6

#629 hotfix numpy>=2.0
  pyfar/classes/orientations.py
  pyfar/dsp/dsp.py
  tests/test_dsp.py
Labels: hot

#637 add header to index
  docs/index.rst
Labels: hot, documentation

#624 Enhance user warning for writing clipped audio files
  pyfar/io/io.py
Labels: bug, io
