Repository pyfar/pyfar, pull requests merged in 2024-05, with the labels that each got.

#596 hotfix: allow None in sh_order setter
  pyfar/classes/coordinates.py
Labels: bug, coordinates, 0.6.6

#599 use intersphinx for numpy and matplotlib absolute links
  pyfar/_concepts/plots.py
  pyfar/classes/audio.py
  pyfar/dsp/dsp.py
  pyfar/dsp/interpolation.py
  pyfar/signals/deterministic.py
  pyfar/utils.py
Labels: documentation

#597 Fix math and description of coordinates
  pyfar/classes/coordinates.py
Labels: documentation, 0.6.6

#605 fix broken docstring of decorated functions
  pyfar/_utils.py
Labels: hot, 0.6.6

#494 Migrate from `flake8` to `ruff`
  .circleci/config.yml
  CONTRIBUTING.rst
  pyproject.toml
  requirements_dev.txt
  setup.cfg
  setup.py
Labels: ci, cookiecutter
