Repository pyfar/pyfar, pull requests merged in 2024-01, with the labels that each got.

#526 Enhance flake8 testing
  .circleci/config.yml
  tests/test_audio_frequency_data.py
  tests/test_audio_signal.py
  tests/test_audio_time_data.py
Labels: ci

#524 hotfix find_within
  pyfar/classes/coordinates.py
  tests/test_coordinates_find.py
Labels: hot, coordinates

#532 Fix bug in concatenate channels
  pyfar/utils.py
  tests/test_utils.py
Labels: hot
