Repository pyfar/pyfar, pull requests merged in 2024-08, with the labels that each got.

#658 Change squeeze in filter class to keep cshape of input signal
  pyfar/classes/filter.py
  tests/test_filter.py
  tests/test_filter_classes.py
  tests/test_fractional_octaves.py
Labels: bug

#653 restructure pyfar doc
  README.rst
  docs/api_reference.rst
  docs/classes.rst
  docs/conf.py
  docs/modules.rst
  docs/pyfar.rst
Labels: documentation

#656 Add complex 2d plots
  pyfar/plot/_line.py
  pyfar/plot/_two_d.py
  pyfar/plot/_utils.py
  pyfar/plot/line.py
  pyfar/plot/two_d.py
  tests/conftest.py
  tests/test_plot.py
  tests/test_plot__utils.py
  tests/test_plot_data/baseline/complex_2d_freq_2d.png
  tests/test_plot_data/baseline/complex_2d_freq_group_delay_2d.png
  tests/test_plot_data/baseline/complex_2d_freq_phase_2d.png
  tests/test_plot_data/baseline/complex_2d_group_delay_2d.png
  tests/test_plot_data/baseline/complex_2d_phase_2d.png
  tests/test_plot_data/baseline/complex_2d_time_2d.png
  tests/test_plot_data/baseline/complex_2d_time_freq_2d.png
  tests/test_plot_data/baseline/freq_default.png
  tests/test_plot_data/baseline/freq_group_delay_left_default.png
  tests/test_plot_data/baseline/freq_group_delay_left_hold.png
  tests/test_plot_data/baseline/freq_group_delay_right_default.png
  tests/test_plot_data/baseline/freq_group_delay_right_hold.png
  tests/test_plot_data/baseline/freq_left_default.png
  tests/test_plot_data/baseline/freq_left_hold.png
  tests/test_plot_data/baseline/freq_phase_left_default.png
  tests/test_plot_data/baseline/freq_phase_left_hold.png
  tests/test_plot_data/baseline/freq_phase_right_default.png
  tests/test_plot_data/baseline/freq_phase_right_hold.png
  tests/test_plot_data/baseline/freq_right_default.png
  tests/test_plot_data/baseline/freq_right_hold.png
  tests/test_plot_data/baseline/group_delay_left_default.png
  tests/test_plot_data/baseline/group_delay_left_hold.png
  tests/test_plot_data/baseline/group_delay_right_default.png
  tests/test_plot_data/baseline/group_delay_right_hold.png
  tests/test_plot_data/baseline/phase_left_default.png
  tests/test_plot_data/baseline/phase_left_hold.png
  tests/test_plot_data/baseline/phase_right_default.png
  tests/test_plot_data/baseline/phase_right_hold.png
  tests/test_plot_data/baseline/spectrogram_unit_ms.png
  tests/test_plot_data/baseline/time_2d_vertical_points-custom.png
  tests/test_plot_data/baseline/time_real_default.png
  tests/test_plot_data/baseline/time_real_hold.png
Labels: complex-signal

#668 implement _return_item for complex signals
  pyfar/classes/audio.py
  tests/test_audio_signal.py
  tests/test_audio_time_data.py
Labels: complex-signal

#672 add side parameter to phase_2d
  pyfar/plot/two_d.py
  tests/test_plot__utils.py
Labels: complex-signal

#670 fix deprecation warnings
  pyfar/classes/coordinates.py
  tests/test_signals.py
Labels: hot, v0.6.9

#644 add deprecation test on cirlce ci
  .circleci/config.yml
  pyfar/classes/coordinates.py
  tests/test_signals.py
Labels: ci, cookiecutter, v0.6.9

#666 fix squeeze in dsp.spectrogram to keep cshape
  pyfar/dsp/dsp.py
  pyfar/plot/_two_d.py
  tests/test_dsp_spectrogram.py
Labels: v0.6.9

#663 change squeeze in gammatone process method
  pyfar/dsp/filter/gammatone.py
  tests/test_filter_gammatone.py
Labels: v0.6.9

#659 Fix squeeze in dsp functions to keep cshape of input signal
  pyfar/dsp/dsp.py
  pyfar/plot/_two_d.py
  tests/test_dsp.py
  tests/test_dsp_interpolation.py
  tests/test_dsp_spectrogram.py
Labels: bug, v0.6.9

#677 don't allow fractional octave smoothing for complex signals
  pyfar/dsp/interpolation.py
  tests/test_dsp_interpolation.py
Labels: complex-signal

#676 Harmonize use of squeeze in pyfar
  pyfar/classes/filter.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/gammatone.py
  pyfar/plot/_two_d.py
  tests/test_dsp.py
  tests/test_dsp_interpolation.py
  tests/test_dsp_spectrogram.py
  tests/test_filter.py
  tests/test_filter_classes.py
  tests/test_filter_gammatone.py
  tests/test_fractional_octaves.py
Labels: dsp, v0.6.9

#674 Disable getting specific samples or frequencies from a signal through slicing
  pyfar/classes/audio.py
  tests/test_audio_frequency_data.py
  tests/test_audio_signal.py
  tests/test_audio_time_data.py
  tests/test_filter_classes.py
Labels: audio, v0.6.9

#665 let numpy handle the broadcasting in Coordinates
  pyfar/classes/coordinates.py
  tests/test_coordinates.py
Labels: v0.6.9

#678 update for new squeeze behavior in dsp
  tests/test_filter.py
Labels: bug, v0.6.9

#622 add workflow which PR Check Label for version Label
  .github/workflows/has_version_label.yml
Labels: ci, v0.6.9

#679 convert readme to markdown
  MANIFEST.in
  README.md
  README.rst
  docs/conf.py
  docs/readme.rst
  requirements_dev.txt
  setup.py
Labels: documentation, v0.6.9

#671 Plot complex spectogram
  pyfar/plot/_two_d.py
  pyfar/plot/_utils.py
  pyfar/plot/two_d.py
  tests/test_plot.py
  tests/test_plot__utils.py
  tests/test_plot_data/baseline/spectrogram_complex_left_default.png
  tests/test_plot_data/baseline/spectrogram_complex_right_default.png
Labels: complex-signal, v0.7.0
