Repository pyfar/pyfar, pull requests merged in 2024-04, with the labels that each got.

#564 Remove restriction for matplotlib version
  requirements_dev.txt
  setup.py
Labels: hot, plot

#557 Remove phase for FFT normalizations 'power' and 'psd'
  pyfar/dsp/fft.py
  tests/test_fft.py
Labels: enhancement, dsp, fft

#567 Complex normalization
  pyfar/classes/audio.py
  pyfar/dsp/dsp.py
  tests/test_audio_signal.py
  tests/test_dsp_energy_power_rms.py
  tests/test_dsp_normalize.py
  tests/test_dsp_spectrogram.py
Labels: complex-signal

#574 Remove examples
  .circleci/config.yml
  CONTRIBUTING.rst
  README.rst
  examples/pyfar_demo.ipynb
  requirements_dev.txt
Labels: documentation, bug

#570 remove unused github workflows
  .github/workflows/assign_to_project.yml
Labels: cookiecutter

#586 Github Action: if PR with tag 'cookiecutter' is merged, it will create an issue in cookiecutter-pypackage
  .github/workflows/create_issue_if_coockiecutter.yml
Labels: ci, cookiecutter

#380 Filterbanks to classes
  .gitignore
  pyfar/dsp/filter/__init__.py
  pyfar/dsp/filter/fractional_octaves.py
  pyfar/io/_codec.py
  tests/test_filter.py
  tests/test_fractional_octaves.py
  tests/test_io.py
  tests/test_signals.py
Labels: enhancement, dsp, filter, v0.7.0

#199 Frequency domain sweep synthesis
  pyfar/signals/__init__.py
  pyfar/signals/deterministic.py
  tests/test_signals.py
Labels: feature, dsp, v0.7.0

#569 fix structure in sphinx and download duplicated doc files from gallery
  .gitignore
  docs/_static/css/custom.css
  docs/_static/favicon.ico
  docs/_templates/navbar-nav.html
  docs/conf.py
  docs/index.rst
  docs/pyfar.rst
  docs/resources/logos/pyfar_logos_fixed_size_pyfar.png
  docs/resources/pyfar.png
  requirements_dev.txt
Labels: documentation, cookiecutter, 0.6.6

#589 Harmonize frequency range parameter
  docs/concepts/resources/fft_norms.py
  docs/concepts/resources/filter_types.py
  pyfar/_utils.py
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/fractional_octaves.py
  pyfar/dsp/filter/gammatone.py
  tests/test_deprecations.py
  tests/test_filter_gammatone.py
  tests/test_fractional_octaves.py
Labels: 0.6.6
