Repository pyfar/pyfar, pull requests merged in 2024-03, with the labels that each got.

#554 Make Coordiantes.show() use equal axes scaling and return Axis object.
  pyfar/classes/coordinates.py
Labels: 0.6.5

#548 fix english in doc
  CONTRIBUTING.rst
Labels: documentation, bug, 0.6.5

#556 Hotfix typos in coordinates figure
  docs/concepts/resources/coordinate_systems.ai
  docs/concepts/resources/coordinate_systems.png
Labels: 0.6.5

#544 replace old naming convention description
  pyfar/_concepts/coordinates.py
Labels: documentation, bug, coordinates, 0.6.5

#549 remove obsolete information from print Coordinates
  pyfar/classes/coordinates.py
Labels: bug, coordinates, 0.6.5

#561 Add support for python 3.12
  .circleci/config.yml
  setup.py
Labels: enhancement, 0.6.5

#560 Adapt doc style from gallery
  docs/_static/css/custom.css
  docs/_static/favicon.ico
  docs/_templates/navbar-nav.html
  docs/conf.py
  docs/index.rst
  docs/resources/logos/pyfar_logos_fixed_size_pyfar.png
  requirements_dev.txt
Labels: documentation, 0.6.5
