Repository pyfar/pyfar, pull requests merged in 2024-10, with the labels that each got.

#712 Update internal documentation for _codec module
  pyfar/io/_codec.py
Labels: documentation, enhancement, v0.8.0

#717 allow sphinx 8
  pyfar/dsp/filter/band_filter.py
  requirements_dev.txt
  setup.py
Labels: documentation, v0.7.1

#718 Improve pyfar.signals.files
  pyfar/signals/files.py
Labels: enhancement, v0.8.0

#715 Python 3.13 support
  .circleci/config.yml
  setup.py
Labels: v0.7.1
