Repository pyfar/pyfar, pull requests merged in 2025-05, with the labels that each got.

#789 apply cookiecutter
  docs/conf.py
Labels: documentation

#800 fix inconstistant docstring format
  pyfar/dsp/fft.py
Labels: documentation

#774 Feature: add density of air
  pyfar/constants/__init__.py
  pyfar/constants/constants.py
  tests/test_constants_utils.py
Labels: feature, constants

#795 Increase TOC depth for left sidebar to 2
  docs/conf.py
Labels: documentation, cookiecutter

#804 Patch: Coordinates._set_points: separate internal checks from setting the variables
  pyfar/classes/coordinates.py
Labels: enhancement, coordinates

#805 Patch: Coordinates._set_weights: separate internal checks from setting the variables
  pyfar/classes/coordinates.py
Labels: coordinates

#806 Update history for 0.7.3 release
  HISTORY.rst
Labels: documentation
