Repository pyfar/pyfar, pull requests merged in 2025-02, with the labels that each got.

#756 Add missing default in `pyfar.FilterIIR.init_state`
  pyfar/classes/filter.py
  tests/test_filter_classes.py
Labels: bug, filter, v0.7.2

#764 HOT: return int array for find_impulse_response_start()
  pyfar/dsp/dsp.py
  tests/test_dsp.py
Labels: hot, dsp, v0.7.2

#748 Remove deprecated parameters in pf.dsp.pad_zero
  pyfar/dsp/dsp.py
  tests/test_deprecations.py
Labels: v0.8.0

#746 remove deprecated freq_range parameter
  pyfar/dsp/dsp.py
  pyfar/dsp/filter/fractional_octaves.py
  pyfar/dsp/filter/gammatone.py
  pyfar/io/io.py
  tests/test_deprecations.py
  tests/test_dsp_deconvolution.py
  tests/test_filter_gammatone.py
  tests/test_signals.py
Labels: v0.8.0

#745 remove deprecated len(pf.Signal)
  pyfar/classes/audio.py
  tests/test_deprecations.py
Labels: v0.8.0

#767 HOT: replace version label check by check for any label
  .github/workflows/has_label.yml
  .github/workflows/has_version_milestone.yml
Labels: hot, ci, cookiecutter

#755 Filter impulse response
  pyfar/classes/filter.py
  tests/test_filter_classes.py
Labels: feature, filter

#769 Fixed some typos
  pyfar/classes/audio.py
  pyfar/classes/transmission_matrix.py
Labels: documentation

#739 speed of sound ideal gas law
  pyfar/constants/__init__.py
  pyfar/constants/speed_of_sound.py
  tests/test_constants_speed_of_sound.py
Labels: feature, constants

#742 hot: fix radius check in find_within
  pyfar/classes/coordinates.py
  tests/test_coordinates_find.py
Labels: hot

#753 Use oaconvolve for FIR process
  pyfar/classes/filter.py
  tests/test_filter_classes.py
Labels: enhancement, dsp

#732 speed of sound calculation
  docs/api_reference.rst
  docs/modules/pyfar.constants.rst
  pyfar/__init__.py
  pyfar/constants/__init__.py
  pyfar/constants/speed_of_sound.py
  tests/test_constants_speed_of_sound.py
Labels: feature, constants

#765 Add filter state setter
  pyfar/classes/filter.py
  tests/test_filter_classes.py
Labels: hot
